export default function Index() {
  return (
    <>
      <section
        className="w-full px-6 pt-3 overflow-hidden bg-white xl:px-8"
        data-tails-scripts="//unpkg.com/alpinejs"
      >
        <div
          className="absolute top-0 left-0 w-full h-3 bg-gradient-to-r from-indigo-700 via-blue-500 to-green-300"
          data-primary="indigo-600"
        ></div>

        <div className="container pt-16 mx-auto text-left md:text-center">
          <div className="relative max-w-4xl mx-auto">
            <h1
              className="pb-2 text-4xl font-extrabold text-left text-transparent sm:text-5xl md:text-6xl md:text-center bg-clip-text bg-gradient-to-r from-indigo-700 via-blue-500 to-green-300"
              data-primary="indigo-600"
            >
              Universal HTTPS Backend
            </h1>

            <p className="mt-8 text-sm text-left text-gray-500 sm:text-base md:text-lg md:max-w-xl md:text-center md:mx-auto">
              Minimalistic setup for running your services with Docker Compose
              behind Traefik with autogenerated HTTPS certificates
            </p>

            <div className="py-6 mt-4">
              <a
                href="https://github.com/starters-dev/https-backend"
                target="_blank"
                className="relative text-2xl group"
                rel="noreferrer"
              >
                <span
                  className="relative z-10 px-5 py-2 font-bold leading-tight text-black bg-white border-4 border-gray-900 rounded-lg group-hover:text-white group-hover:bg-black"
                  data-rounded="rounded-lg"
                >
                  Github↗
                </span>
                <span
                  className="absolute top-0 right-0 w-full h-14 -mt-2.5 -mr-0.5 bg-black rounded-lg"
                  data-rounded="rounded-lg"
                ></span>
              </a>
            </div>
          </div>
        </div>
      </section>
      <section className="pt-2 bg-white">
        <div className="max-w-4xl px-20 mx-auto">
          <div className="grid grid-cols-1 mt-8 sm:grid-cols-2 md:grid-cols-3 gap-x-10 lg:gap-x-16 gap-y-20">
            <div className="">
              <svg
                className="w-10 h-10 text-blue-600"
                data-primary="blue-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"
                  className=""
                ></path>
              </svg>
              <h3 className="mt-4 mb-2 text-base font-semibold leading-tight text-gray-900 lg:text-lg">
                Extensible
              </h3>
              <p className="text-sm text-gray-500 lg:text-base">
                New Docker service (e.g. frontend, api) can be easily and
                intuitively added.
              </p>
            </div>

            <div className="">
              <svg
                className="w-10 h-10 text-blue-600"
                data-primary="blue-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                ></path>
              </svg>
              <h3 className="mt-4 mb-2 text-base font-semibold leading-tight text-gray-900 lg:text-lg">
                Clean Code
              </h3>
              <p className="text-sm text-gray-500 lg:text-base">
                Ready scripts for general purposes.
              </p>
            </div>

            <div className="">
              <svg
                className="w-10 h-10 text-blue-600"
                data-primary="blue-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                  className=""
                ></path>
              </svg>
              <h3 className="mt-4 mb-2 text-base font-semibold leading-tight text-gray-900 lg:text-lg">
                HTTPS
              </h3>
              <p className="text-sm text-gray-500 lg:text-base">
                Certificates are automatically generate
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="py-2 mt-8">
        <div className="px-10 mx-auto max-w-7xl">
          <div className="flex justify-center items-center flex-row">
            <span className="text-sm text-gray-400">
              HTTPS Backend is a part of{" "}
              <a
                href="https://starters.dev"
                className="underline"
                target="_blank"
                rel="noreferrer"
              >
                starters.dev
              </a>{" "}
              collection.
            </span>
          </div>
        </div>
      </section>
    </>
  );
}
